# =============================================================================
# JAIA Azure AI Foundry - デモ/開発用の軽量構成
# =============================================================================
# Azure AI Foundry Serviceのみをプロビジョニング（VNet, Container Apps等は不要）
#
# 使用方法:
#   cd infrastructure/terraform/azure/demo
#   az login
#   terraform init
#   terraform plan
#   terraform apply
#
# 適用後:
#   terraform output -json > azure_config.json
#   または ../../scripts/setup_azure.ps1 を使用
# =============================================================================

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.80"
    }
  }
}

provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
    cognitive_account {
      purge_soft_deleted_accounts_on_destroy = true
    }
  }
}

# =============================================================================
# Variables
# =============================================================================

variable "location" {
  description = "Azure region (japaneast推奨)"
  type        = string
  default     = "eastus"

  # japaneastではOpenAIモデルが制限される場合があるため
  # eastus をデフォルトに設定
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "demo"
}

variable "app_name" {
  description = "Application name prefix"
  type        = string
  default     = "jaia"
}

variable "model_name" {
  description = "Azure AI Foundry model to deploy"
  type        = string
  default     = "gpt-5.2-chat"

  # 利用可能なモデル: gpt-5.2-chat, gpt-4o, gpt-4o-mini
  # gpt-5.2-chat はeastus2等の対応リージョンで利用可
}

variable "model_version" {
  description = "Model version"
  type        = string
  default     = "2025-12-11"
}

variable "model_capacity" {
  description = "Deployment capacity (TPM in thousands)"
  type        = number
  default     = 10
}

# =============================================================================
# Resource Group
# =============================================================================

resource "azurerm_resource_group" "demo" {
  name     = "rg-${var.app_name}-${var.environment}"
  location = var.location

  tags = {
    Application = "JAIA"
    Environment = var.environment
    Purpose     = "Demo / Development"
    ManagedBy   = "Terraform"
  }
}

# =============================================================================
# Azure AI Foundry Service
# =============================================================================

resource "azurerm_cognitive_account" "openai" {
  name                  = "aoai-${var.app_name}-${var.environment}"
  location              = azurerm_resource_group.demo.location
  resource_group_name   = azurerm_resource_group.demo.name
  kind                  = "OpenAI"
  sku_name              = "S0"
  custom_subdomain_name = "aoai-${var.app_name}-${var.environment}"

  # デモ用: ネットワーク制限なし
  network_acls {
    default_action = "Allow"
  }

  tags = azurerm_resource_group.demo.tags
}

# =============================================================================
# Model Deployment
# =============================================================================

resource "azurerm_cognitive_deployment" "model" {
  name                 = "${var.model_name}-deployment"
  cognitive_account_id = azurerm_cognitive_account.openai.id

  model {
    format  = "OpenAI"
    name    = var.model_name
    version = var.model_version
  }

  scale {
    type     = "GlobalStandard"
    capacity = var.model_capacity
  }
}

# =============================================================================
# Outputs - backend/.env に設定する値
# =============================================================================

output "azure_foundry_endpoint" {
  description = "Azure AI Foundry endpoint URL"
  value       = azurerm_cognitive_account.openai.endpoint
}

output "azure_foundry_api_key" {
  description = "Azure AI Foundry primary API key"
  value       = azurerm_cognitive_account.openai.primary_access_key
  sensitive   = true
}

output "azure_foundry_deployment" {
  description = "Model deployment name"
  value       = azurerm_cognitive_deployment.model.name
}

output "model_name" {
  description = "Deployed model name"
  value       = var.model_name
}

output "resource_group" {
  description = "Resource group name"
  value       = azurerm_resource_group.demo.name
}

output "env_config" {
  description = "backend/.env に設定する値"
  value       = <<-EOT
    # === Azure AI Foundry Config (generated by Terraform) ===
    LLM_PROVIDER=azure_foundry
    LLM_MODEL=${var.model_name}
    AZURE_FOUNDRY_ENDPOINT=${azurerm_cognitive_account.openai.endpoint}
    AZURE_FOUNDRY_DEPLOYMENT=${azurerm_cognitive_deployment.model.name}
    AZURE_FOUNDRY_API_VERSION=2024-10-21
  EOT
  # Note: API key is sensitive and output separately
}
